import { AIClient } from './ai-client.js';
import type { MastroConfig, DocumentationType, DocumentationContext, DocumentationConfig, DocumentationOutput } from '../types/index.js';
export declare class DocumentationEngine {
    private aiClient;
    private config;
    constructor(config: MastroConfig, aiClient: AIClient);
    generateDocumentation(type: DocumentationType, context: DocumentationContext, config: DocumentationConfig): Promise<DocumentationOutput>;
    private generateApiDocumentation;
    private generateArchitectureDocumentation;
    private generateUserGuideDocumentation;
    private generateReadmeDocumentation;
    private generateComponentDocumentation;
    private generateDeploymentDocumentation;
    private parseDocumentationSections;
    private generateMermaidDiagrams;
    private generateSystemArchitectureDiagram;
    private generateUserFlowDiagram;
    private injectDiagrams;
    private extractApiReferences;
    private extractArchitectureReferences;
    private extractUserGuideReferences;
    private extractComponentReferences;
    private generateTroubleshootingDocumentation;
    private generateChangelogDocumentation;
    private generateContributingDocumentation;
    private generateSecurityDocumentation;
    private generatePerformanceDocumentation;
    private generateTestingDocumentation;
    private generateContributingDiagrams;
    private generatePerformanceDiagrams;
    private generateTestingDiagrams;
    private generateGitWorkflowDiagram;
    private generatePerformanceTimelineDiagram;
    private generateTestingMindmapDiagram;
    private extractTroubleshootingReferences;
    private extractContributingReferences;
    private extractSecurityReferences;
    private extractPerformanceReferences;
    private extractTestingReferences;
    private generateWorkflowDocumentation;
    private generateIntegrationDocumentation;
    private generateAllDocumentation;
    private generateWorkflowDiagrams;
    private generateMastroFlowDiagram;
    private generateWorkflowSequenceDiagram;
    private extractWorkflowReferences;
    private extractIntegrationReferences;
}
//# sourceMappingURL=doc-engine.d.ts.map