import { BaseCommand } from '../base/command.js';
export default class Split extends BaseCommand {
    static description: string;
    static examples: string[];
    static flags: {
        'auto-stage': import("@oclif/core/lib/interfaces/parser.js").BooleanFlag<boolean>;
        'dry-run': import("@oclif/core/lib/interfaces/parser.js").BooleanFlag<boolean>;
        format: import("@oclif/core/lib/interfaces/parser.js").OptionFlag<string, import("@oclif/core/lib/interfaces/parser.js").CustomOptions>;
        interactive: import("@oclif/core/lib/interfaces/parser.js").BooleanFlag<boolean>;
        'interactive-review': import("@oclif/core/lib/interfaces/parser.js").BooleanFlag<boolean>;
        'min-boundary-size': import("@oclif/core/lib/interfaces/parser.js").OptionFlag<number, import("@oclif/core/lib/interfaces/parser.js").CustomOptions>;
        'max-boundary-size': import("@oclif/core/lib/interfaces/parser.js").OptionFlag<number, import("@oclif/core/lib/interfaces/parser.js").CustomOptions>;
        flow: import("@oclif/core/lib/interfaces/parser.js").BooleanFlag<boolean>;
        commit: import("@oclif/core/lib/interfaces/parser.js").BooleanFlag<boolean>;
        config: import("@oclif/core/lib/interfaces/parser.js").OptionFlag<string, import("@oclif/core/lib/interfaces/parser.js").CustomOptions>;
        verbose: import("@oclif/core/lib/interfaces/parser.js").BooleanFlag<boolean>;
        'no-cache': import("@oclif/core/lib/interfaces/parser.js").BooleanFlag<boolean>;
    };
    private renderer;
    private interactiveUI;
    private boundaryAnalyzer;
    private workflowManager;
    run(): Promise<void>;
    private outputTerminal;
    private outputJSON;
    private outputMarkdown;
    private handleInteractiveMode;
    private handleAutoStaging;
    private displayNextSteps;
    private handleMergeBoundaries;
    private handleSplitBoundary;
    private handleReorderCommits;
    private handleModifyMessages;
    private validateFlags;
    private handleFlowMode;
    private handleCommitMode;
    private stageFilesForBoundary;
    private createCommitForBoundary;
    private formatCommitMessage;
    private displayFinalCommitSummary;
    private generateSimpleCommitMessage;
    private getChangeTypeIcon;
    private determineChangeType;
    private handleInteractiveReviewMode;
    private displayBoundaryOverview;
    private reviewBoundaryInteractively;
    private attemptBoundaryStaging;
    private handleStagingFailure;
    private modifyBoundaryInteractively;
    private splitBoundaryFiles;
    private removeProblematicFiles;
    private editBoundaryCommitMessage;
    private editBoundaryFiles;
    private reorderBoundaryFiles;
    private viewFileDetailedDiff;
    private runBoundaryValidation;
    private showDetailedBoundaryDiff;
    private displayInteractiveReviewSummary;
    private handleFailedBoundariesRecovery;
    private saveFailedBoundariesForReview;
    private attemptManualRecovery;
    private showRecoveryRecommendations;
}
//# sourceMappingURL=split.d.ts.map